print("Hello, World!")
print(5+3)
print("Python", "is", "Fun!")
print("She said, \"Hello!\"")
print("Python is easy\nand its fun.")
print("python\tis\tfun")
print("The result is", 42)
print(12345)
print(3.14159)
print("Dollar sign: $")
print("apple", "banana", "cherry", sep=", ")
print("Hello,", end= " ")
print("World!")
print("Python! " * 3)
print("\u2764")
print()
print("Hello " + "World")
print(True)
print(False)
print(1.2e3)
print("""This is a multiline
print statement.""")
print("This is a backslash: \\")